# the environment name
name: notebook
# the channels where conda will look for the packages
channels:
  - conda-forge
  - defaults
# the packages that will be installed
dependencies:
  - pip=24.0
  - python=3.12
  - jupyterlab=4.2.3
# the packages that will be installed using pip
  - pip:
      - black==24.4.2
      - coloredlogs==15.0.1
      - ipympl==0.9.4
      - matplotlib==3.8.4
      - notebook==7.2.1
      - pandas==2.2.2 # 2.9.0
      - plotly_express==0.4.1
      - python-dotenv==1.0.
      - streamlit==1.36.0
      - openpyxl==3.1.5
      - seaborn==0.13.2
      - scikit-learn==1.5.1
      - tensorflow==2.17.0